import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "CalcApp",
  description: "Generated by KYK",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      
      </body>
    </html>
  );
}
